### ISSUE TITLE
Pulumi Port

### ISSUE THREAD

**Issue by yukimotochern** [SigNoz/terraform-provider-signoz#16]
Pulumi provide a way to map terraform provider to pulumi counter part.
The template repo: [pulumi-tf-provider-boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate).
The pulumi-terraform-bridge: https://github.com/pulumi/pulumi-terraform-bridge
The relevant doc from pulumi: https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/
Would you consider port this to pulumi?

**Comment by grandwizard28** [comment]
Hey @yukimotochern,
Thank you for opening an issue. Would you be open to implementing this?

**Comment by yukimotochern** [comment]
@grandwizard28 I am open to implement this.

**Comment by grandwizard28** [comment]
Great! Have assigned the issue to you!

**Comment by yukimotochern** [comment]
This may require another repo, but I could do it on the weekends anyway.
